[package]
name = "gastronomy-cli"
version = "0.4.0"
edition = "2021"
repository = "https://github.com/SundaeSwap-finance/gastronomy"
description = "Gastronomy CLI"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
tokio = { version = "1.40", features = ["full"] }
clap = { version = "4", features = ["derive", "env"] }
gastronomy = { path = "../gastronomy" }
uplc = { git = "https://github.com/SundaeSwap-finance/aiken.git", rev = "e5a60f3" }
# uplc = { path = "../aiken/crates/uplc" }
ratatui = { version = "0.26", features = ["all-widgets"] }
crossterm = "0.27"
color-eyre = "0.6"
# pretty = "0.12.3"

[package.metadata.dist]
dist = true
