[workspace]

members = [
    "gastronomy",
    "gastronomy-cli",
    "gastronomy-ui",
]

resolver = "2"

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

[workspace.metadata.release]
shared-version = true
tag-name = "v{{version}}"
